language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  # g++ 4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

  - sudo apt-get install build-essential m4 libgmp3-dev cmake

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; CC="gcc-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq binutils-gold clang-3.5; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; CC="clang-3.5"; fi

  - cd StormLib
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - cd bncsutil/src/bncsutil
  - make
  - sudo make install
  - cd ../../..

script:
  - make
  - sudo make install

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: false
  irc:
    channels:
      - "irc.quakenet.org#clan007"
    <<: *notifications-policy

